version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my_blog_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_blog
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_blog_network

volumes:
  db-data:

networks:
  my_blog_network:
